# fly.toml app configuration file generated for marketplace-broken-waterfall-6247 on 2025-07-03T04:19:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marketplace-broken-waterfall-6247'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
