package zjg.marketplace.core.entity.base;

import java.util.Date;
import java.util.UUID;

public abstract class BaseEntity {
    protected BaseEntity() {
        id = UUID.randomUUID().toString();
        createdAt = new Date();
        updatedAt = new Date();
    }
    private String id; // Auto generated by database!
    private Date createdAt;
    private Date updatedAt;

    // Getter
    public String getId() {
        return id;
    }
    public Date getCreatedAt() {
        return createdAt;
    }
    public Date getUpdatedAt() {
        return updatedAt;
    }

    // Setter
    protected void setId(String id) {
        this.id = id;
    }
    protected void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    protected void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    // Events
    protected void onUpdate() {
        this.updatedAt = new Date();
    }
}
