package zjg.marketplace.application.services.product;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import zjg.marketplace.application.dto.product.ProductInput;
import zjg.marketplace.application.resolver.facade.ServiceResolverFacade;
import zjg.marketplace.application.service.promisse.CreateService;
import zjg.marketplace.application.service.promisse.DeleteService;
import zjg.marketplace.application.service.promisse.FindService;
import zjg.marketplace.application.service.promisse.UpdateService;
import zjg.marketplace.core.product.entity.Product;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.concurrent.ConcurrentLinkedQueue;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ProductCommandServiceTest {

    @Autowired
    public ServiceResolverFacade facade;
    private FindService<Product> fService;
    private CreateService<Product, ProductInput> createService;
    private UpdateService<Product, ProductInput> updateService;
    private DeleteService<Product> deleteService;
    private static ConcurrentLinkedQueue<String> ids = new ConcurrentLinkedQueue<>();

    @BeforeEach
    void contextLoads() {
        updateService = facade.resolveUpdate(Product.class, ProductInput.class);
        createService = facade.resolveCreate(Product.class, ProductInput.class);
        deleteService = facade.resolveDelete(Product.class);
        fService = facade.resolveFind(Product.class);
    }
    @Test
    @Order(1)
    public void insertItems() {
        for (int i = 1; i < 500; i++) {
            var input = makeInput(i);
            var p = createService.create(input).block(Duration.ofSeconds(2));
            ids.add(p.getId());
        }
    }

    @Test
    @Order(2)
    public void putAll() {
        for (var id : ids) {
            var input = makeInput(-1);
            updateService.update(input, id).block(Duration.ofSeconds(2));
        }
    }

    @Test
    @Order(3)
    public void removeAll() {
        for (var id : ids) {
            deleteService.deleteById(id).block(Duration.ofSeconds(5));
        };
    }

/*  @Test
    @Order(4)
    public void removeAll2() {
        fService.get(2, 5500, false).flatMap(x -> {
            return deleteService.deleteById(x.getId());
        }).collectList().block(Duration.ofSeconds(15));
    }*/


    private ProductInput makeInput(int index) {
        var input = new ProductInput();
        input.setAmount(BigDecimal.TEN);
        input.setDescription("Ignore1" + index);
        input.setTitle("System - Autogenerated!" + index);
        return input;
    }
}
