# SERVER ------------------------------
server:
  port: ${PORT:8080}
  address: 0.0.0.0
# DOCUMENTATION ----------------------------
springdoc:
  swagger-ui:
    enabled: false
    path: /swagger
  api-docs:
    enabled: false
    path: /docs
# SPRING ---------------------------------
spring:
  application:
    name: marketplace
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 5 minutes (in ms)
  data:
    mongodb:
      uri: ${DATABASE_URI}
      auto-index-creation: true
    redis:
      url: ${REDIS_URL}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

# CUSTOM ------------------------
aws:
  endpoint: ${AWS_ENDPOINT}
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_IMAGE_BUCKET}
logging:
  loki:
    url: ${LOKI_CONNECTION_URI}