# SERVER ---------------------------
server:
 port: 5055
 address: 0.0.0.0

# SWAGGER / DOCUMENTATION ----------
springdoc:
 swagger-ui:
  enabled: true
  path: /swagger
 api-docs:
  enabled: true

# SPRING ---------------------------
spring:
 application:
  name: marketplace
 cache:
  type: redis
  redis:
   time-to-live: 300000 # 5 minutes (in ms)
 redis:
  url: redis://localhost:6379
 data:
  mongodb:
   uri: mongodb://localhost:27017/User_dev
   auto-index-creation: true
  jackson:
   deserialization:
    FAIL_ON_UNKNOWN_PROPERTIES: false

# ============= CUSTOM =============== #
# AWS -------------------------
aws:
 endpoint: http://localhost:4566
 region: sa-east-01
 accessKey: test
 secretKey: test
 s3:
  bucket: "marketplace-images"
 redis:
  host: localhost
  port: 6379

# Logging -------------------------
logging:
 loki:
  url: http://localhost:3100/loki/api/v1/push