package zjg.marketplace.application.services;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import reactor.core.publisher.Mono;
import zjg.marketplace.application.dto.product.ProductInput;
import zjg.marketplace.application.resolver.facade.ServiceResolverFacade;
import zjg.marketplace.application.service.promisse.CreateService;
import zjg.marketplace.application.service.promisse.DeleteService;
import zjg.marketplace.application.service.promisse.FindService;
import zjg.marketplace.application.service.promisse.UpdateService;
import zjg.marketplace.core.product.entity.Product;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ProductCommandServiceTest {

    @Autowired
    public ServiceResolverFacade facade;
    private FindService<Product> fService;
    private CreateService<Product, ProductInput> createService;
    private UpdateService<Product, ProductInput> updateService;
    private DeleteService<Product> deleteService;
    private ConcurrentLinkedQueue<String> ids = new ConcurrentLinkedQueue<>();

    @BeforeEach
    void contextLoads() {
        createService = facade.resolveCreate(Product.class, ProductInput.class);
        deleteService = facade.resolveDelete(Product.class);
        fService = facade.resolveFind(Product.class);
    }
    @Test
    @Order(1)
    public void insertItems() {
        for (int i = 1; i < 500; i++) {
            var input = makeInput(i);
            var id = createService.create(input).block(Duration.ofSeconds(2));
            if(id == null) System.out.println("pica grossa");
            else System.out.println("pica fina + " + id.getId());
            ids.add(id.getId());
        }
    }

    @Test
    @Order(2)
    public void putAll() {
        ids.forEach(id -> {
            var input = makeInput(-1);
            updateService.update(input, id).block(Duration.ofSeconds(2));
        });
    }

    @Test
    @Order(3)
    public void removeAll() {

        System.out.println(ids.stream().count() + " SIZE LIST");
        for (var id : ids) {
            deleteService.deleteById(id).block(Duration.ofSeconds(5));
        };
    }

/*    @Test
    @Order(4)
    public void removeAll2() {
        fService.get(2, 5500, false).flatMap(x -> {
            return deleteService.deleteById(x.getId());
        }).collectList().block(Duration.ofSeconds(15));
    }*/


    private ProductInput makeInput(int index) {
        var input = new ProductInput();
        input.setAmount(BigDecimal.TEN);
        input.setDescription("Ignore1");
        input.setTitle("System - Autogenerated!" + index);
        return input;
    }
}
