package zjg.marketplace.product.factory;

import zjg.marketplace.application.dto.product.ProductInput;

import java.math.BigDecimal;

public class ProductInputFactoryTest {
      public static ProductInput factory() {
            var input = new ProductInput();
            input.setAmount(BigDecimal.TEN);
            input.setDescription("Ignore1");
            input.setTitle("System - Autogenerated!");
            return input;
      }
}
